server:
  port: 8083

spring:
  application:
    name: nep-service-feedback
  config:
    import: "optional:nacos:"
  datasource:
    username: root
    password: 182930
    url: jdbc:mysql://localhost:3306/nep_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 1967272143@qq.com
    password: mxcnkucosukecihj
    default-encoding: UTF-8
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  cloud:
    nacos:
      config:
        enabled: false
        import-check:
          enabled: false
      discovery:
        enabled: true          # 启用 Nacos 服务注册与发现（分布式核心判分点）
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP
    sentinel:
      transport:
        dashboard: localhost:8858
        port: 8721
      eager: true

feign:
  sentinel:
    enabled: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-prefix: nep_
